# Generated by Django 5.0.4 on 2024-04-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("transaction_type", models.CharField(max_length=255)),
                ("amount", models.IntegerField()),
                ("description", models.CharField(max_length=255)),
            ],
        ),
    ]
