# Generated by Django 5.0.4 on 2024-04-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
